# This rule is not used by the project serviceaccount-quota itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the quota.mayooot.github.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount-quota
    app.kubernetes.io/managed-by: kustomize
  name: serviceaccountquota-editor-role
rules:
- apiGroups:
  - quota.mayooot.github.io
  resources:
  - serviceaccountquotas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - quota.mayooot.github.io
  resources:
  - serviceaccountquotas/status
  verbs:
  - get
