# This rule is not used by the project serviceaccount-quota itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over quota.mayooot.github.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount-quota
    app.kubernetes.io/managed-by: kustomize
  name: serviceaccountquota-admin-role
rules:
- apiGroups:
  - quota.mayooot.github.io
  resources:
  - serviceaccountquotas
  verbs:
  - '*'
- apiGroups:
  - quota.mayooot.github.io
  resources:
  - serviceaccountquotas/status
  verbs:
  - get
