apiVersion: quota.mayooot.github.io/v1alpha1
kind: ServiceAccountQuota
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount-quota
    app.kubernetes.io/managed-by: kustomize
  name: serviceaccountquota-sample
spec:
  # TODO(user): Add fields here
